USE zawodySportowe;
Go
-- Zrób zestawienie zawodników w wieku 17-19 którzy wygrali zawody w
--roku 2025
SELECT 
	Z.IMIÊ,
	Z.NAZWISKO,
	Z.ZAWODNIK_ID,
	Z.DATA_URODZENIA,
	COUNT(*) AS LICZBA_WYGRANYCH_2025

FROM ZAWODNIK Z
	JOIN UCZESTNIK U ON Z.ZAWODNIK_ID = U.ZAWODNIK_ID
	JOIN WYNIK W ON U.UCZESTNICTWO_ID = W.UCZESTNICTWO_ID
	JOIN ZAWODY ZW ON U.ZAWODY_ID = ZW.ZAWODY_ID

WHERE 
	W.POZYCJA = 1
	AND YEAR(ZW.DATA_ZAWODOW) = 2025
	AND W.KATEGORIA_ID IN ('M18', 'K18')

GROUP BY 
	Z.IMIÊ, 
	Z.NAZWISKO,
	Z.ZAWODNIK_ID,
	Z.DATA_URODZENIA

ORDER BY
	LICZBA_WYGRANYCH_2025 DESC

