USE zawodySportowe;
Go

-- Sporz¹dŸ zestawienie 5 krajów z których zawodnicy najwiêcej razy byli
-- na podiumSELECT TOP 5	K.NAZWA_KRAJU,	COUNT(*) AS LICZBA_PODIOWFROM KRAJ K	JOIN ZAWODNIK Z ON K.KRAJ_ID = Z.KRAJ_ID	JOIN UCZESTNIK U ON Z.ZAWODNIK_ID = U.ZAWODNIK_ID	JOIN WYNIK W ON U.UCZESTNICTWO_ID = W.UCZESTNICTWO_IDWHERE	W.POZYCJA <=3GROUP BY	K.NAZWA_KRAJUORDER BY 	LICZBA_PODIOW DESC