USE zawodySportowe;
GO

-- Sporz¹dŸ zestawienie które poka¿e z jakiego kraju jest najwiêcej
-- zawodników w danej kategorii

SELECT TOP 1 WITH TIES
	KAT.KATEGORIA_ID,
	K.NAZWA_KRAJU,
	COUNT(*) AS LICZBA_ZAWODNIKÓW

FROM KRAJ K
	JOIN ZAWODNIK Z ON K.KRAJ_ID = Z.KRAJ_ID
	JOIN UCZESTNIK U ON Z.ZAWODNIK_ID = U.ZAWODNIK_ID
	JOIN WYNIK W ON U.UCZESTNICTWO_ID = W.UCZESTNICTWO_ID
	JOIN KATEGORIA KAT ON W.KATEGORIA_ID = KAT.KATEGORIA_ID

GROUP BY 
	KAT.KATEGORIA_ID,
	K.NAZWA_KRAJU

ORDER BY
	RANK() OVER(PARTITION BY KAT.KATEGORIA_ID ORDER BY COUNT(*) DESC);
