USE zawodySportowe
GO

--przyklad update

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3009;

UPDATE UCZESTNIK
SET STATUS_ZAPISU=N'Opłacony'
WHERE UCZESTNICTWO_ID=3009;

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3009;

-- update kaskadowy

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3009;
SELECT * FROM WYNIK WHERE UCZESTNICTWO_ID = 3009;

UPDATE UCZESTNIK 
SET UCZESTNICTWO_ID=3100
WHERE UCZESTNICTWO_ID = 3009;

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3100;
SELECT * FROM WYNIK WHERE UCZESTNICTWO_ID = 3100;

