USE zawodySportowe;
GO

--przyklad 1 (np. zawody odwolane) usuwanie
SELECT * FROM ZAWODY WHERE ZAWODY_ID = 1;
SELECT count(*) as [Liczba Uczestników] FROM UCZESTNIK WHERE ZAWODY_ID = 1;
SELECT count(*) as [Liczba Punktów] FROM PUNKTY_KONTROLNE WHERE ZAWODY_ID = 1;

DELETE FROM ZAWODY WHERE ZAWODY_ID = 1;

SELECT * FROM ZAWODY WHERE ZAWODY_ID = 1;
SELECT count(*) as [Liczba Uczestników] FROM UCZESTNIK WHERE ZAWODY_ID = 1;
SELECT count(*) as [Liczba Punktów] FROM PUNKTY_KONTROLNE WHERE ZAWODY_ID = 1;

--przyklad 2 usuwanie

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM WYNIK WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM MIĘDZYCZASY WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM ZDJĘCIA WHERE UCZESTNICTWO_ID = 3002;

DELETE FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3002;

SELECT * FROM UCZESTNIK WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM WYNIK WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM MIĘDZYCZASY WHERE UCZESTNICTWO_ID = 3002;
SELECT * FROM ZDJĘCIA WHERE UCZESTNICTWO_ID = 3002;

