USE zawodySportowe;
GO

CREATE TABLE KRAJ (
    KRAJ_ID INT PRIMARY KEY,
    NAZWA_KRAJU NVARCHAR(100) NOT NULL,
    KOD_ISO3 CHAR(3) NOT NULL
);

CREATE TABLE MIASTO (
    MIASTO_ID INT PRIMARY KEY,
    NAZWA NVARCHAR(100) NOT NULL,
    KRAJ_ID INT NOT NULL REFERENCES KRAJ(KRAJ_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ZAWODY (
    ZAWODY_ID INT PRIMARY KEY,
    NAZWA NVARCHAR(100) NOT NULL,
    MIASTO_ID INT NOT NULL REFERENCES MIASTO(MIASTO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    DATA_ZAWODOW DATE,
    EDYCJA INT
);

CREATE TABLE ZAWODNIK (
    ZAWODNIK_ID INT PRIMARY KEY,
    IMIĘ NVARCHAR(50) NOT NULL,
    NAZWISKO NVARCHAR(50) NOT NULL,
    DATA_URODZENIA DATE NOT NULL,
    KRAJ_ID INT NOT NULL REFERENCES KRAJ(KRAJ_ID) ON DELETE NO ACTION 
);

CREATE TABLE UCZESTNIK (
    UCZESTNICTWO_ID INT PRIMARY KEY,
    ZAWODNIK_ID INT NOT NULL REFERENCES ZAWODNIK(ZAWODNIK_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    ZAWODY_ID INT NOT NULL REFERENCES ZAWODY(ZAWODY_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    NUMER_STARTOWY INT,
    STATUS_ZAPISU NVARCHAR(50) NOT NULL DEFAULT(N'Opłacony') CHECK (STATUS_ZAPISU IN (N'Opłacony', N'Nieopłacony')),
    CONSTRAINT UQ_Uczestnik UNIQUE (ZAWODNIK_ID, ZAWODY_ID)
);

CREATE TABLE KATEGORIA (
    KATEGORIA_ID NVARCHAR(3) PRIMARY KEY,
    PŁEĆ CHAR(1) NOT NULL CHECK (PŁEĆ IN ('K','M')),
    WIEK_MINIMALNY INT,
    WIEK_MAKSYMALNY INT
);

CREATE TABLE WYNIK (
    UCZESTNICTWO_ID INT PRIMARY KEY REFERENCES UCZESTNIK(UCZESTNICTWO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CZAS_UKOŃCZENIA TIME,
    POZYCJA INT,
    KATEGORIA_ID NVARCHAR(3) NOT NULL REFERENCES KATEGORIA(KATEGORIA_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    STATUS NVARCHAR(50)
);

CREATE TABLE PUNKTY_KONTROLNE (
    PUNKT_ID INT PRIMARY KEY,
    ODLEGŁOŚĆ INT,
    ZAWODY_ID INT NOT NULL REFERENCES ZAWODY(ZAWODY_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MIĘDZYCZASY (
   PUNKT_ID INT NOT NULL REFERENCES PUNKTY_KONTROLNE(PUNKT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION, 
   UCZESTNICTWO_ID INT NOT NULL REFERENCES UCZESTNIK(UCZESTNICTWO_ID) ON DELETE CASCADE ON UPDATE CASCADE, 
   CZAS_NA_PUNKCIE TIME NOT NULL,
   PRIMARY KEY (PUNKT_ID, UCZESTNICTWO_ID)
);

CREATE TABLE ZDJĘCIA (
    ZDJĘCIE_ID INT PRIMARY KEY IDENTITY(1,1),
    UCZESTNICTWO_ID INT NOT NULL REFERENCES UCZESTNIK(UCZESTNICTWO_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    ŚCIEŻKA NVARCHAR(255) NOT NULL UNIQUE,
    MOMENT_CZASOWY TIME
);
GO